In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
 
# 定义网络结构
class FullyConnectedNet(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim, num_hidden_layers=3):
        super(FullyConnectedNet, self).__init__()
        self.layers = nn.ModuleList()
        # 输入层到第一个隐藏层
        self.layers.append(nn.Linear(input_dim, hidden_dim))
        self.layers.append(nn.ReLU())
        # 添加中间的隐藏层
        for _ in range(num_hidden_layers - 1):
            self.layers.append(nn.Linear(hidden_dim, hidden_dim))
            self.layers.append(nn.ReLU())
        # 最后一个隐藏层到输出层
        self.layers.append(nn.Linear(hidden_dim, output_dim))
    
    def forward(self, x):
        for layer in self.layers:
            x = layer(x)
        return x
 # 设置参数
input_dim = 10  # 输入维度
hidden_dim = 10  # 隐藏层节点数
output_dim = 5  # 输出类别数
num_hidden_layers = 3  # 隐藏层数
 
# 初始化网络
net = FullyConnectedNet(input_dim, hidden_dim, output_dim, num_hidden_layers)
 
# 构造维度为10的单个样本输入数据，随机初始化网络参数
input_data = torch.randn(1, input_dim)  # 1个样本，每个样本10维
print("Input Data:\n", input_data)
 
# 前向反馈后打印网络输出
output = net(input_data)
print("Network Output:\n", output)

Input Data:
 tensor([[-1.4256, -0.6011, -0.3646, -1.1002, -1.0500,  0.1506, -1.3114,  0.0738,
          0.8800, -0.1778]])
Network Output:
 tensor([[ 0.0313,  0.1783,  0.2369,  0.1024, -0.1433]],
       grad_fn=<AddmmBackward0>)


上课版

In [4]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [5]:
tensor = torch.randn(1, 10)
# 假设我们有一个样本，其类别索引为3（例如，在一个有4个类别的数据集中）
class_index = torch.tensor([3])  # 一个包含类别索引的张量

# 使用F.one_hot生成one-hot张量
y = F.one_hot(class_index, num_classes=5)  # num_classes是类别的总数

In [6]:
class FullyConnectedNet(nn.Module):
    def __init__(self, input_size, output_size=5):
        super(FullyConnectedNet, self).__init__()
        # 定义第一个隐藏层
        self.fc1 = nn.Linear(input_size, 7)
        # 定义第二个隐藏层
        self.fc2 = nn.Linear(7, 7)
        # 定义第三个隐藏层
        self.fc3 = nn.Linear(7, 7)
        # 定义输出层
        self.fc4 = nn.Linear(7, output_size)
        self.softmax = nn.Softmax(dim=1)

    def forward(self, x):
        # 应用第一个隐藏层并使用ReLU激活函数
        x = F.relu(self.fc1(x))
        # 应用第二个隐藏层并使用ReLU激活函数
        x = F.relu(self.fc2(x))
        # 应用第三个隐藏层并使用ReLU激活函数
        x = F.relu(self.fc3(x))
        # 应用输出层
        x = self.fc4(x)
        return self.softmax(x)

In [7]:
dim1 = tensor.shape[1]

In [8]:
model = FullyConnectedNet(input_size=dim1)

In [9]:
out = model(tensor)
print(out)

tensor([[0.1840, 0.1934, 0.2140, 0.2155, 0.1932]], grad_fn=<SoftmaxBackward0>)


In [10]:
l = (torch.log(out)*y).sum()

In [11]:
l.backward()

In [12]:
params = model.parameters()

# 遍历并打印参数
for param in params:
    print(param.grad)

tensor([[-0.0057,  0.0038, -0.0157, -0.0138, -0.0074,  0.0040, -0.0166, -0.0180,
         -0.0222, -0.0051],
        [-0.0036,  0.0024, -0.0100, -0.0087, -0.0047,  0.0025, -0.0105, -0.0114,
         -0.0140, -0.0032],
        [ 0.0000, -0.0000,  0.0000,  0.0000,  0.0000, -0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [-0.0141,  0.0094, -0.0389, -0.0340, -0.0182,  0.0099, -0.0409, -0.0445,
         -0.0548, -0.0126],
        [ 0.0000, -0.0000,  0.0000,  0.0000,  0.0000, -0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [ 0.0000, -0.0000,  0.0000,  0.0000,  0.0000, -0.0000,  0.0000,  0.0000,
          0.0000,  0.0000],
        [ 0.0000, -0.0000,  0.0000,  0.0000,  0.0000, -0.0000,  0.0000,  0.0000,
          0.0000,  0.0000]])
tensor([-0.0144, -0.0091,  0.0000, -0.0356,  0.0000,  0.0000,  0.0000])
tensor([[-0.0144, -0.0298, -0.0000, -0.0423, -0.0000, -0.0000, -0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000, 